In [10]:
# To get today date,month and year and time also
import datetime
d = datetime.datetime.now()
print(d.day)
print(d.month)
print(d.year)
print(d.minute)
print(d.second)

21
11
2019
51
31


In [19]:
import calendar
cal = calendar.month(2019,11)
print(cal)

   November 2019
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30



In [28]:
a = calendar.weekday(2019,11,21)
print(calendar.day_name[a]) # To print weekday 

Thursday


In [39]:
# The strftime() method returns a string representing date and time using date, time or datetime object.
from datetime import datetime
n = datetime.now()
print(n.strftime('%d %B %Y'))

21 November 2019


In [41]:
from datetime import datetime

# datetime object containing current date and time
now = datetime.now()
 
print("now =", now)

# dd/mm/YY H:M:S
dt_string = now.strftime("%d/%m/%Y %H:%M:%S %p")
print("date and time =", dt_string)

now = 2019-11-21 10:52:28.780894
date and time = 21/11/2019 10:52:28 AM


In [52]:
from tkinter import *
tk = Tk()
canvas = Canvas(tk, width=400, height=400)
canvas.pack()
canvas.create_arc(10,10,200,100,extent=180,style=ARC)
mainloop()

In [ ]:
import tkinter as tk 
r = tk.Tk() 
r.title('Counting Seconds') 
button = tk.Button(r, text='Stop', width=25, command=r.destroy) 
button.pack() 
r.mainloop()

In [1]:
from tkinter import *
master = Tk() 
w = Canvas(master, width=40, height=60) 
w.pack() 
canvas_height=20
canvas_width=200
y = int(canvas_height / 2) 
w.create_line(0, y, canvas_width, y ) 
mainloop() 

In [6]:
# Turtle
import turtle
wn = turtle.Screen()
wn.bgcolor("blue")
wn.title("Turtle")
turtle.done()

# Python Libraries for Data Analysis 

## 1. Many popular Python toolboxes/libraries..
>  * NumPy
>  * Scipy
>  * Pandas
>  * SciKit Learn
## 2. Visualization libraries
> * matplotlib
> * Seaborn
> * Ploty

# i)NumPy(Numerical Python)

# 1-Dimensional Array

In [9]:
import numpy as np
data = np.random.randn(2,3)
data

array([[ 0.66499334,  0.07713965,  0.30367788],
       [-0.31410335, -1.003708  , -0.29567331]])

In [10]:
data*10

array([[  6.64993342,   0.77139653,   3.03677883],
       [ -3.14103349, -10.03708   ,  -2.95673311]])

In [11]:
data + data

array([[ 1.32998668,  0.15427931,  0.60735577],
       [-0.6282067 , -2.007416  , -0.59134662]])

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
ar = np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
ar[5:8]=12

In [35]:
ar_slice = ar[5:8]
ar_slice

array([12, 12, 12])

In [36]:
ar_slice[1]=1234

In [42]:
ar_slice[:]=64
ar_slice

array([64, 64, 64])

In [43]:
ar

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

# 2-Dimensional Array Slicing

In [44]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [49]:
arr2d[1,:2]

array([4, 5])

In [50]:
arr2d[:,1]

array([2, 5, 8])

In [54]:
arr2d[:2,1]=9
arr2d

array([[1, 9, 3],
       [4, 9, 6],
       [7, 0, 9]])

In [75]:
arr2d[0:3,[0,2]] # to delete the particular column.

array([[1, 3],
       [4, 6],
       [7, 9]])

In [77]:
arr2d[[0,2],:] # to delete the particular row.

array([[1, 9, 3],
       [7, 0, 9]])

In [81]:
names=['bob','narmada','jeo']
data = np.random.randn(3,2)
data

array([[ 1.53136874, -0.76719153],
       [-0.53774168, -0.60600226],
       [ 0.10334296, -1.13164654]])

In [85]:
ar1 = np.empty((8,4))
ar1

array([[1.30353406e-311, 1.09682573e-321, 0.00000000e+000,
        0.00000000e+000],
       [2.22660000e-307, 3.16251369e+180, 1.96086892e+243,
        4.56251821e+174],
       [1.29060661e+248, 1.16071791e-028, 7.37108894e+228,
        1.04796651e-142],
       [2.86752281e+161, 1.39547881e-142, 1.14449682e+243,
        2.03914759e+180],
       [6.19635191e+223, 1.40210426e-142, 6.35296675e-062,
        1.78818445e-047],
       [1.16467185e-028, 2.60218818e+251, 7.26813884e+223,
        5.87449201e+294],
       [8.42244189e+252, 6.01409647e+175, 9.06707527e+271,
        1.09476743e-065],
       [4.27255605e+180, 2.87521412e+161, 2.19965310e-094,
        9.97328607e-143]])

In [86]:
for i in range(8):
    ar1[i]=i
ar1

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [88]:
ar1[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [89]:
ar1[[-3,-1]]# based on negative index we can get the row value.

array([[5., 5., 5., 5.],
       [7., 7., 7., 7.]])

In [95]:
ar = np.arange(32).reshape(8,4) # by using reshape we can form the matrix.
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [96]:
ar[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [108]:
ar[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [116]:
ar = np.arange(16).reshape(2,2,4) # first 2 is numer matrix,next 2 number of rows,4
ar

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [110]:
ar1.ravel() # by using ravel method we can from 2d to 1-d array.

array([0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4.,
       4., 4., 4., 5., 5., 5., 5., 6., 6., 6., 6., 7., 7., 7., 7.])

In [124]:
ar.transpose(1,0,2) #2,2,4 =>0,1,2(indexes of 2,2,4)=>(2,0,1)=[4,2,2]=>4m,2r,2c.

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [123]:
ar

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

# Pandas Data Structure

>  
* Series
* DataFrame

In [129]:
import pandas as pd
sd = pd.Series([4,7,5,3],index=['d','b','a','c'])
sd

d    4
b    7
a    5
c    3
dtype: int64

In [131]:
sd['d']=10  # update the value
sd

d    10
b     7
a     5
c     3
dtype: int64

In [132]:
sd['c'] # get the value

3

In [133]:
sd['a']=-5

In [134]:
sd

d    10
b     7
a    -5
c     3
dtype: int64

In [135]:
sd>0

d     True
b     True
a    False
c     True
dtype: bool

In [136]:
np.exp(sd)

d    22026.465795
b     1096.633158
a        0.006738
c       20.085537
dtype: float64

In [137]:
sd

d    10
b     7
a    -5
c     3
dtype: int64

In [138]:
'b' in sd # check if the index is avaible or not.

True

In [147]:
sdata = {'China':4000,'Texs':4300,'india':7098} # here keys are indexing values are data.
sdata = pd.Series(sdata)
sdata

China    4000
Texs     4300
india    7098
dtype: int64

In [148]:
states=['China','bnlg','india']
sdata = pd.Series(sdata,states) # if the index position is matching then directly returns the value. if not matching it returns the value is NaN.
sdata

China    4000.0
bnlg        NaN
india    7098.0
dtype: float64

In [150]:
pd.isnull(sdata)

China    False
bnlg      True
india    False
dtype: bool

In [151]:
pd.notnull(sdata)

China     True
bnlg     False
india     True
dtype: bool

In [152]:
sdata + sd => 

China   NaN
a       NaN
b       NaN
bnlg    NaN
c       NaN
d       NaN
india   NaN
dtype: float64